// Generated by scripts/build-product-images.ts. Do not edit.
export type ProductMediaRole = 'thumbnail' | 'card' | 'detail';

export type GeneratedProductImage = Readonly<{
  src: string;
  alt: string;
  width: number;
  height: number;
  role: ProductMediaRole;
}>;

const registry = {
  'protein-powder': {
    thumbnail: {
      src: '/images/products/protein-powder.thumbnail.0f037ab2f377.320.webp',
      alt: 'Protein Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/protein-powder.card.f3774c601746.720.webp',
      alt: 'Protein Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/protein-powder.detail.e7ef7379ca60.1200.webp',
      alt: 'Protein Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-oats': {
    thumbnail: {
      src: '/images/products/powdered-oats.thumbnail.b1c147731743.320.webp',
      alt: 'Powdered Oats powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-oats.card.7c2c2f0ca102.720.webp',
      alt: 'Powdered Oats powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-oats.detail.d87972cc8127.1200.webp',
      alt: 'Powdered Oats powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'cocoa-powder': {
    thumbnail: {
      src: '/images/products/cocoa-powder.thumbnail.1ea2687732db.320.webp',
      alt: 'Cocoa Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/cocoa-powder.card.af483a563e35.720.webp',
      alt: 'Cocoa Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/cocoa-powder.detail.8a8f0f9f4649.1200.webp',
      alt: 'Cocoa Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-peanut-butter': {
    thumbnail: {
      src: '/images/products/powdered-peanut-butter.thumbnail.24fc1dd91e36.320.webp',
      alt: 'Powdered Peanut Butter powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-peanut-butter.card.f01401f9a67c.720.webp',
      alt: 'Powdered Peanut Butter powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-peanut-butter.detail.8be3c6059f8a.1200.webp',
      alt: 'Powdered Peanut Butter powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'tomato-powder': {
    thumbnail: {
      src: '/images/products/tomato-powder.thumbnail.de3c49a1193e.320.webp',
      alt: 'Tomato Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/tomato-powder.card.06aecc8e3966.720.webp',
      alt: 'Tomato Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/tomato-powder.detail.27bce5db2a9c.1200.webp',
      alt: 'Tomato Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'mushroom-powder': {
    thumbnail: {
      src: '/images/products/mushroom-powder.thumbnail.5322f6eaf85b.320.webp',
      alt: 'Mushroom Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/mushroom-powder.card.b811150e8fd5.720.webp',
      alt: 'Mushroom Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/mushroom-powder.detail.7f28d8938abb.1200.webp',
      alt: 'Mushroom Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'roasted-garlic-powder': {
    thumbnail: {
      src: '/images/products/roasted-garlic-powder.thumbnail.c8649c5a3b43.320.webp',
      alt: 'Roasted Garlic Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/roasted-garlic-powder.card.cd142f4a545a.720.webp',
      alt: 'Roasted Garlic Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/roasted-garlic-powder.detail.008440083fdc.1200.webp',
      alt: 'Roasted Garlic Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'electrolyte-powder': {
    thumbnail: {
      src: '/images/products/electrolyte-powder.thumbnail.dddb747610d2.320.webp',
      alt: 'Electrolyte Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/electrolyte-powder.card.4f5035d7b85e.720.webp',
      alt: 'Electrolyte Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/electrolyte-powder.detail.c4f2f2bf96cf.1200.webp',
      alt: 'Electrolyte Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'recovery-cocoa': {
    thumbnail: {
      src: '/images/products/recovery-cocoa.thumbnail.8ac081f44923.320.webp',
      alt: 'Recovery Cocoa powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/recovery-cocoa.card.7d3d8588c22f.720.webp',
      alt: 'Recovery Cocoa powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/recovery-cocoa.detail.f8b5bc1bb822.1200.webp',
      alt: 'Recovery Cocoa powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'beetroot-powder': {
    thumbnail: {
      src: '/images/products/beetroot-powder.thumbnail.a11d789a76b7.320.webp',
      alt: 'Beetroot Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/beetroot-powder.card.db74a0fe9fb9.720.webp',
      alt: 'Beetroot Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/beetroot-powder.detail.82e786f2e088.1200.webp',
      alt: 'Beetroot Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'pea-protein-powder': {
    thumbnail: {
      src: '/images/products/pea-protein-powder.thumbnail.20ba6a9ce8d0.320.webp',
      alt: 'Pea Protein Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/pea-protein-powder.card.d5b9ec2032dd.720.webp',
      alt: 'Pea Protein Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/pea-protein-powder.detail.98c5fd5113f4.1200.webp',
      alt: 'Pea Protein Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'banana-powder': {
    thumbnail: {
      src: '/images/products/banana-powder.thumbnail.6775054f1bee.320.webp',
      alt: 'Banana Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/banana-powder.card.456f0e2f28d1.720.webp',
      alt: 'Banana Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/banana-powder.detail.94a1c8813abb.1200.webp',
      alt: 'Banana Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'oat-milk-powder': {
    thumbnail: {
      src: '/images/products/oat-milk-powder.thumbnail.117568599bf3.320.webp',
      alt: 'Oat Milk Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/oat-milk-powder.card.3637a113894c.720.webp',
      alt: 'Oat Milk Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/oat-milk-powder.detail.7e9e55011b2b.1200.webp',
      alt: 'Oat Milk Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'matcha-powder': {
    thumbnail: {
      src: '/images/products/matcha-powder.thumbnail.6b46412ae55d.320.webp',
      alt: 'Matcha Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/matcha-powder.card.cfbd32c49a2f.720.webp',
      alt: 'Matcha Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/matcha-powder.detail.279e8f33950a.1200.webp',
      alt: 'Matcha Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'coffee-powder': {
    thumbnail: {
      src: '/images/products/coffee-powder.thumbnail.4a4f446044cb.320.webp',
      alt: 'Coffee Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/coffee-powder.card.42cd54872326.720.webp',
      alt: 'Coffee Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/coffee-powder.detail.029d04035325.1200.webp',
      alt: 'Coffee Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'strawberry-milk-powder': {
    thumbnail: {
      src: '/images/products/strawberry-milk-powder.thumbnail.e145ba7b7b5a.320.webp',
      alt: 'Strawberry Milk Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/strawberry-milk-powder.card.6f8ea36f536e.720.webp',
      alt: 'Strawberry Milk Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/strawberry-milk-powder.detail.5b00d1a8903b.1200.webp',
      alt: 'Strawberry Milk Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'lemonade-powder': {
    thumbnail: {
      src: '/images/products/lemonade-powder.thumbnail.1e36230b836c.320.webp',
      alt: 'Lemonade Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/lemonade-powder.card.4d40f454dacf.720.webp',
      alt: 'Lemonade Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/lemonade-powder.detail.b1eb1ad55d8b.1200.webp',
      alt: 'Lemonade Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'chai-powder': {
    thumbnail: {
      src: '/images/products/chai-powder.thumbnail.a6a08ff30d10.320.webp',
      alt: 'Chai Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/chai-powder.card.0a6b50a24a7e.720.webp',
      alt: 'Chai Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/chai-powder.detail.22df35ccdc7c.1200.webp',
      alt: 'Chai Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'cherry-soda-powder': {
    thumbnail: {
      src: '/images/products/cherry-soda-powder.thumbnail.0ecbbda36dfe.320.webp',
      alt: 'Cherry Soda Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/cherry-soda-powder.card.9a9aa51f2cfe.720.webp',
      alt: 'Cherry Soda Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/cherry-soda-powder.detail.9fa97bab7ce7.1200.webp',
      alt: 'Cherry Soda Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'laundry-powder': {
    thumbnail: {
      src: '/images/products/laundry-powder.thumbnail.b113dff3d37a.320.webp',
      alt: 'Laundry Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/laundry-powder.card.3af05c14d34e.720.webp',
      alt: 'Laundry Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/laundry-powder.detail.0ef021657b84.1200.webp',
      alt: 'Laundry Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'dishwasher-powder': {
    thumbnail: {
      src: '/images/products/dishwasher-powder.thumbnail.25c018fd219d.320.webp',
      alt: 'Dishwasher Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/dishwasher-powder.card.7d2a8c5454cb.720.webp',
      alt: 'Dishwasher Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/dishwasher-powder.detail.0e7941c6115b.1200.webp',
      alt: 'Dishwasher Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'carpet-refresh-powder': {
    thumbnail: {
      src: '/images/products/carpet-refresh-powder.thumbnail.911d67e69aa8.320.webp',
      alt: 'Carpet Refresh Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/carpet-refresh-powder.card.b7bad70a32e9.720.webp',
      alt: 'Carpet Refresh Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/carpet-refresh-powder.detail.5760593edaed.1200.webp',
      alt: 'Carpet Refresh Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'window-powder': {
    thumbnail: {
      src: '/images/products/window-powder.thumbnail.51c855ccba23.320.webp',
      alt: 'Window Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/window-powder.card.6525e7db49f1.720.webp',
      alt: 'Window Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/window-powder.detail.3e341d6f56e6.1200.webp',
      alt: 'Window Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'sock-drawer-powder': {
    thumbnail: {
      src: '/images/products/sock-drawer-powder.thumbnail.76afddce8f91.320.webp',
      alt: 'Sock Drawer Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/sock-drawer-powder.card.7217376c4dc1.720.webp',
      alt: 'Sock Drawer Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/sock-drawer-powder.detail.d66b65575f52.1200.webp',
      alt: 'Sock Drawer Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'bookshelf-dusting-powder': {
    thumbnail: {
      src: '/images/products/bookshelf-dusting-powder.thumbnail.ac6de7e29cc3.320.webp',
      alt: 'Bookshelf Dusting Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/bookshelf-dusting-powder.card.ed114e89c3ba.720.webp',
      alt: 'Bookshelf Dusting Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/bookshelf-dusting-powder.detail.b91589b90c0d.1200.webp',
      alt: 'Bookshelf Dusting Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'mop-bucket-powder': {
    thumbnail: {
      src: '/images/products/mop-bucket-powder.thumbnail.e1d571f41282.320.webp',
      alt: 'Mop Bucket Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/mop-bucket-powder.card.be78b036c8e6.720.webp',
      alt: 'Mop Bucket Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/mop-bucket-powder.detail.1c7af9ed62a1.1200.webp',
      alt: 'Mop Bucket Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-campfire': {
    thumbnail: {
      src: '/images/products/powdered-campfire.thumbnail.f2b54254ac92.320.webp',
      alt: 'Powdered Campfire powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-campfire.card.05b2a7cf0f6d.720.webp',
      alt: 'Powdered Campfire powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-campfire.detail.28d812571ec7.1200.webp',
      alt: 'Powdered Campfire powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-beach': {
    thumbnail: {
      src: '/images/products/powdered-beach.thumbnail.9840e7b7d514.320.webp',
      alt: 'Powdered Beach powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-beach.card.e37a395b4360.720.webp',
      alt: 'Powdered Beach powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-beach.detail.25568108aa46.1200.webp',
      alt: 'Powdered Beach powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'trail-dust-powder': {
    thumbnail: {
      src: '/images/products/trail-dust-powder.thumbnail.ef0d98d21079.320.webp',
      alt: 'Trail Dust Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/trail-dust-powder.card.3771c085cb8b.720.webp',
      alt: 'Trail Dust Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/trail-dust-powder.detail.c4a52d225d57.1200.webp',
      alt: 'Trail Dust Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'morning-fog-powder': {
    thumbnail: {
      src: '/images/products/morning-fog-powder.thumbnail.316aaf08ebe5.320.webp',
      alt: 'Morning Fog Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/morning-fog-powder.card.7101f8f339f8.720.webp',
      alt: 'Morning Fog Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/morning-fog-powder.detail.4935e4625c16.1200.webp',
      alt: 'Morning Fog Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'pine-needle-powder': {
    thumbnail: {
      src: '/images/products/pine-needle-powder.thumbnail.52288614570b.320.webp',
      alt: 'Pine Needle Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/pine-needle-powder.card.86846c7d8b29.720.webp',
      alt: 'Pine Needle Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/pine-needle-powder.detail.1d343571fb67.1200.webp',
      alt: 'Pine Needle Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'summit-air-powder': {
    thumbnail: {
      src: '/images/products/summit-air-powder.thumbnail.f56e81cf5b98.320.webp',
      alt: 'Summit Air Powder powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/summit-air-powder.card.8eb39a30c0be.720.webp',
      alt: 'Summit Air Powder powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/summit-air-powder.detail.976768f6fae2.1200.webp',
      alt: 'Summit Air Powder powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-house': {
    thumbnail: {
      src: '/images/products/powdered-house.thumbnail.34ba9bd90460.320.webp',
      alt: 'Powdered House powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-house.card.ea83ed8711b7.720.webp',
      alt: 'Powdered House powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-house.detail.f84c7099d81e.1200.webp',
      alt: 'Powdered House powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-wifi': {
    thumbnail: {
      src: '/images/products/powdered-wifi.thumbnail.e2bfebfcf195.320.webp',
      alt: 'Powdered Wi-Fi powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-wifi.card.8171f37ad8bf.720.webp',
      alt: 'Powdered Wi-Fi powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-wifi.detail.2b432f71404c.1200.webp',
      alt: 'Powdered Wi-Fi powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-tuesday': {
    thumbnail: {
      src: '/images/products/powdered-tuesday.thumbnail.caa2d63dad80.320.webp',
      alt: 'Powdered Tuesday powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-tuesday.card.a4a8f0cefad2.720.webp',
      alt: 'Powdered Tuesday powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-tuesday.detail.0b6d02cb0f9d.1200.webp',
      alt: 'Powdered Tuesday powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-meeting': {
    thumbnail: {
      src: '/images/products/powdered-meeting.thumbnail.ae957f267b94.320.webp',
      alt: 'Powdered Meeting powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-meeting.card.7ff4444cdfd9.720.webp',
      alt: 'Powdered Meeting powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-meeting.detail.120e160b43fc.1200.webp',
      alt: 'Powdered Meeting powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-spare-key': {
    thumbnail: {
      src: '/images/products/powdered-spare-key.thumbnail.5ad22bf0f173.320.webp',
      alt: 'Powdered Spare Key powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-spare-key.card.40c1c9ccb18f.720.webp',
      alt: 'Powdered Spare Key powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-spare-key.detail.36be0f17e658.1200.webp',
      alt: 'Powdered Spare Key powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-queue': {
    thumbnail: {
      src: '/images/products/powdered-queue.thumbnail.824b7dc1eb2d.320.webp',
      alt: 'Powdered Queue powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-queue.card.637826f99cbc.720.webp',
      alt: 'Powdered Queue powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-queue.detail.98ef19952e32.1200.webp',
      alt: 'Powdered Queue powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-five-more-minutes': {
    thumbnail: {
      src: '/images/products/powdered-five-more-minutes.thumbnail.d4f4afebcfcc.320.webp',
      alt: 'Powdered Five More Minutes powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-five-more-minutes.card.eaef9e7ca817.720.webp',
      alt: 'Powdered Five More Minutes powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-five-more-minutes.detail.d12fb198d6bb.1200.webp',
      alt: 'Powdered Five More Minutes powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-gravity': {
    thumbnail: {
      src: '/images/products/powdered-gravity.thumbnail.5bb53f5e354a.320.webp',
      alt: 'Powdered Gravity powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-gravity.card.0075e541ae5c.720.webp',
      alt: 'Powdered Gravity powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-gravity.detail.254027076fb0.1200.webp',
      alt: 'Powdered Gravity powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-silence': {
    thumbnail: {
      src: '/images/products/powdered-silence.thumbnail.37b7fe46db9a.320.webp',
      alt: 'Powdered Silence powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-silence.card.6c31b2701bb8.720.webp',
      alt: 'Powdered Silence powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-silence.detail.d38b88888556.1200.webp',
      alt: 'Powdered Silence powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-moonlight': {
    thumbnail: {
      src: '/images/products/powdered-moonlight.thumbnail.a44b80f70b2f.320.webp',
      alt: 'Powdered Moonlight powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-moonlight.card.6c64c0598aa3.720.webp',
      alt: 'Powdered Moonlight powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-moonlight.detail.0b489ead3d56.1200.webp',
      alt: 'Powdered Moonlight powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-weekend': {
    thumbnail: {
      src: '/images/products/powdered-weekend.thumbnail.3b38f4b29b6a.320.webp',
      alt: 'Powdered Weekend powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-weekend.card.9c7b90779855.720.webp',
      alt: 'Powdered Weekend powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-weekend.detail.f96a0e4f2b6e.1200.webp',
      alt: 'Powdered Weekend powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-horizon': {
    thumbnail: {
      src: '/images/products/powdered-horizon.thumbnail.d14bdab0beae.320.webp',
      alt: 'Powdered Horizon powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-horizon.card.fb4eacdf5e12.720.webp',
      alt: 'Powdered Horizon powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-horizon.detail.0ec202d4411d.1200.webp',
      alt: 'Powdered Horizon powder bag',
      width: 1200,
      height: 1200,
    },
  },
  'powdered-water': {
    thumbnail: {
      src: '/images/products/powdered-water.thumbnail.41f00273c528.320.webp',
      alt: 'Powdered Water powder bag',
      width: 320,
      height: 320,
    },
    card: {
      src: '/images/products/powdered-water.card.3cc72d1b45cd.720.webp',
      alt: 'Powdered Water powder bag',
      width: 720,
      height: 720,
    },
    detail: {
      src: '/images/products/powdered-water.detail.47fbd7edef5f.1200.webp',
      alt: 'Powdered Water powder bag',
      width: 1200,
      height: 1200,
    },
  },
} as const;

export const PRODUCT_MEDIA_REGISTRY: Readonly<
  Record<string, Readonly<Record<ProductMediaRole, GeneratedProductImage>>>
> = Object.fromEntries(
  Object.entries(registry).map(([id, images]) => [
    id,
    Object.fromEntries(
      Object.entries(images).map(([role, image]) => [role, { ...image, role }]),
    ) as Readonly<Record<ProductMediaRole, GeneratedProductImage>>,
  ]),
);

export function getProductMedia(
  imageSetId: string | null | undefined,
  role: ProductMediaRole,
): GeneratedProductImage | undefined {
  return imageSetId ? PRODUCT_MEDIA_REGISTRY[imageSetId]?.[role] : undefined;
}

export function getProductMediaSet(
  imageSetId: string | null | undefined,
): readonly GeneratedProductImage[] {
  const media = imageSetId ? PRODUCT_MEDIA_REGISTRY[imageSetId] : undefined;
  return media ? [media.thumbnail, media.card, media.detail] : [];
}
