import { createPackaging, type CatalogProduct } from '../model.js';

export const drinksProducts = [
  {
    id: 14,
    name: 'Matcha Powder',
    description: 'Ceremonial-style matcha powder, 30g. Whisk it until your calendar feels cleaner.',
    price_cents: 1895,
    compare_at_price_cents: null,
    category: 'Drinks',
    stock_count: 33,
    sales_count: 520,
    newest_rank: 14,
    image_set_id: 'matcha-powder',
    slug: 'matcha-powder',
    consumption_warning: null,
    packaging: createPackaging('#476b35', '#77a94f', 'M', 'DRK-01', '30g'),
  },
  {
    id: 15,
    name: 'Coffee Powder',
    description:
      'Instant single-origin coffee powder, 100g. A cup of coffee with no visible beans.',
    price_cents: 1495,
    compare_at_price_cents: 1795,
    category: 'Drinks',
    stock_count: 48,
    sales_count: 610,
    newest_rank: 15,
    image_set_id: 'coffee-powder',
    slug: 'coffee-powder',
    consumption_warning: null,
    packaging: createPackaging('#56382d', '#8a5b3d', 'C', 'DRK-02', '100g'),
  },
  {
    id: 16,
    name: 'Strawberry Milk Powder',
    description: 'Strawberry milk drink mix, 350g. Pink milk, pending water.',
    price_cents: 1095,
    compare_at_price_cents: null,
    category: 'Drinks',
    stock_count: 52,
    sales_count: 270,
    newest_rank: 16,
    image_set_id: 'strawberry-milk-powder',
    slug: 'strawberry-milk-powder',
    consumption_warning: null,
    packaging: createPackaging('#d85475', '#ef9aac', 'SM', 'DRK-03', '350g'),
  },
  {
    id: 17,
    name: 'Lemonade Powder',
    description: 'Sharp lemonade powder, 400g. Stir, chill, and accept summer by committee.',
    price_cents: 995,
    compare_at_price_cents: null,
    category: 'Drinks',
    stock_count: 58,
    sales_count: 305,
    newest_rank: 17,
    image_set_id: 'lemonade-powder',
    slug: 'lemonade-powder',
    consumption_warning: null,
    packaging: createPackaging('#d4ad25', '#f1e36e', 'L', 'DRK-04', '400g'),
  },
  {
    id: 18,
    name: 'Chai Powder',
    description: 'Spiced chai powder, 250g. Tea leaves have been spared the meeting.',
    price_cents: 1195,
    compare_at_price_cents: 1395,
    category: 'Drinks',
    stock_count: 37,
    sales_count: 350,
    newest_rank: 18,
    image_set_id: 'chai-powder',
    slug: 'chai-powder',
    consumption_warning: null,
    packaging: createPackaging('#a85e29', '#c98950', 'CH', 'DRK-05', '250g'),
  },
  {
    id: 19,
    name: 'Cherry Soda Powder',
    description: 'Cherry soda drink mix, 180g. Bubbles sold separately by physics.',
    price_cents: 895,
    compare_at_price_cents: null,
    category: 'Drinks',
    stock_count: 46,
    sales_count: 225,
    newest_rank: 19,
    image_set_id: 'cherry-soda-powder',
    slug: 'cherry-soda-powder',
    consumption_warning: null,
    packaging: createPackaging('#b52d45', '#dc4862', 'CS', 'DRK-06', '180g'),
  },

  // Household â€” useful-looking, explicitly not edible.,
] as const satisfies readonly CatalogProduct[];
