import {
  createCatalogProducts,
  createPackaging,
  type CatalogProductDraft,
} from '../model.js';

export const drinksProducts = createCatalogProducts([
  {
    id: 14,
    name: 'Matcha Powder',
    description: 'Ceremonial-style matcha powder, 30g. Whisk it until your calendar feels cleaner.',
    price_cents: 1895,
    compare_at_price_cents: null,
    category: 'Drinks',
    stock_count: 33,
    sales_count: 520,
    active: true,
    created_at: '2025-01-14T00:00:00.000Z',
    tags: [
      { key: 'matcha', label: 'Matcha' },
      { key: 'tea', label: 'Tea' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: { key: 'tea', label: 'Tea' },
      intendedUse: { key: 'drink-preparation', label: 'Drink preparation' },
      storageGuidance: null,
    },
    image_set_id: 'matcha-powder',
    slug: 'matcha-powder',
    packaging: createPackaging('#476b35', '#77a94f', 'M', 'DRK-01', '30g'),
  },
  {
    id: 15,
    name: 'Coffee Powder',
    description:
      'Instant single-origin coffee powder, 100g. A cup of coffee with no visible beans.',
    price_cents: 1495,
    compare_at_price_cents: 1795,
    category: 'Drinks',
    stock_count: 48,
    sales_count: 610,
    active: true,
    created_at: '2025-01-15T00:00:00.000Z',
    tags: [
      { key: 'coffee', label: 'Coffee' },
      { key: 'instant', label: 'Instant' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: { key: 'coffee', label: 'Coffee' },
      intendedUse: { key: 'drink-preparation', label: 'Drink preparation' },
      storageGuidance: null,
    },
    image_set_id: 'coffee-powder',
    slug: 'coffee-powder',
    packaging: createPackaging('#56382d', '#8a5b3d', 'C', 'DRK-02', '100g'),
  },
  {
    id: 16,
    name: 'Strawberry Milk Powder',
    description: 'Strawberry milk drink mix, 350g. Pink milk, pending water.',
    price_cents: 1095,
    compare_at_price_cents: null,
    category: 'Drinks',
    stock_count: 52,
    sales_count: 270,
    active: true,
    created_at: '2025-01-16T00:00:00.000Z',
    tags: [
      { key: 'milk-drink', label: 'Milk drink' },
      { key: 'strawberry', label: 'Strawberry' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: { key: 'pink', label: 'Pink' },
      source: { key: 'strawberry', label: 'Strawberry' },
      intendedUse: { key: 'drink-preparation', label: 'Drink preparation' },
      storageGuidance: null,
    },
    image_set_id: 'strawberry-milk-powder',
    slug: 'strawberry-milk-powder',
    packaging: createPackaging('#d85475', '#ef9aac', 'SM', 'DRK-03', '350g'),
  },
  {
    id: 17,
    name: 'Lemonade Powder',
    description: 'Sharp lemonade powder, 400g. Stir, chill, and accept summer by committee.',
    price_cents: 995,
    compare_at_price_cents: null,
    category: 'Drinks',
    stock_count: 58,
    sales_count: 305,
    active: true,
    created_at: '2025-01-17T00:00:00.000Z',
    tags: [
      { key: 'lemonade', label: 'Lemonade' },
      { key: 'drink-mix', label: 'Drink mix' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: { key: 'drink-preparation', label: 'Drink preparation' },
      storageGuidance: null,
    },
    image_set_id: 'lemonade-powder',
    slug: 'lemonade-powder',
    packaging: createPackaging('#d4ad25', '#f1e36e', 'L', 'DRK-04', '400g'),
  },
  {
    id: 18,
    name: 'Chai Powder',
    description: 'Spiced chai powder, 250g. Tea leaves have been spared the meeting.',
    price_cents: 1195,
    compare_at_price_cents: 1395,
    category: 'Drinks',
    stock_count: 37,
    sales_count: 350,
    active: true,
    created_at: '2025-01-18T00:00:00.000Z',
    tags: [
      { key: 'chai', label: 'Chai' },
      { key: 'spiced', label: 'Spiced' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: { key: 'drink-preparation', label: 'Drink preparation' },
      storageGuidance: null,
    },
    image_set_id: 'chai-powder',
    slug: 'chai-powder',
    packaging: createPackaging('#a85e29', '#c98950', 'CH', 'DRK-05', '250g'),
  },
  {
    id: 19,
    name: 'Cherry Soda Powder',
    description: 'Cherry soda drink mix, 180g. Bubbles sold separately by physics.',
    price_cents: 895,
    compare_at_price_cents: null,
    category: 'Drinks',
    stock_count: 46,
    sales_count: 225,
    active: true,
    created_at: '2025-01-19T00:00:00.000Z',
    tags: [
      { key: 'cherry', label: 'Cherry' },
      { key: 'soda', label: 'Soda' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: { key: 'cherry', label: 'Cherry' },
      intendedUse: { key: 'drink-preparation', label: 'Drink preparation' },
      storageGuidance: null,
    },
    image_set_id: 'cherry-soda-powder',
    slug: 'cherry-soda-powder',
    packaging: createPackaging('#b52d45', '#dc4862', 'CS', 'DRK-06', '180g'),
  },
] as const satisfies readonly CatalogProductDraft[]);
