import {
  createdAtFromNewestRank,
  createCatalogProducts,
  createPackaging,
  type CatalogProductDraft,
  NOT_FOR_CONSUMPTION,
} from '../model.js';

export const householdProducts = createCatalogProducts([
  {
    id: 20,
    name: 'Laundry Powder',
    description: 'Cedar laundry powder, 1kg. For clothes that have seen things.',
    price_cents: 1595,
    compare_at_price_cents: null,
    category: 'Household',
    stock_count: 54,
    sales_count: 445,
    active: true,
    created_at: createdAtFromNewestRank(20),
    tags: [
      { key: 'laundry', label: 'Laundry' },
      { key: 'cedar', label: 'Cedar' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: { key: 'laundry-care', label: 'Laundry care' },
      storageGuidance: null,
    },
    image_set_id: 'laundry-powder',
    slug: 'laundry-powder',
    packaging: createPackaging('#2b789d', '#e7eef0', 'LP', 'HOU-01', '1kg', NOT_FOR_CONSUMPTION),
  },
  {
    id: 21,
    name: 'Dishwasher Powder',
    description: 'Citrus dishwasher powder, 800g. Plates receive a fresh start.',
    price_cents: 1395,
    compare_at_price_cents: 1695,
    category: 'Household',
    stock_count: 43,
    sales_count: 320,
    active: true,
    created_at: createdAtFromNewestRank(21),
    tags: [
      { key: 'dishwasher', label: 'Dishwasher' },
      { key: 'citrus', label: 'Citrus' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: { key: 'dishwasher-cleaning', label: 'Dishwasher cleaning' },
      storageGuidance: null,
    },
    image_set_id: 'dishwasher-powder',
    slug: 'dishwasher-powder',
    packaging: createPackaging('#438e89', '#e2eee0', 'DP', 'HOU-02', '800g', NOT_FOR_CONSUMPTION),
  },
  {
    id: 22,
    name: 'Carpet Refresh Powder',
    description: 'Dry carpet refresh powder, 500g. Vacuum after the room has reflected.',
    price_cents: 1295,
    compare_at_price_cents: null,
    category: 'Household',
    stock_count: 30,
    sales_count: 160,
    active: true,
    created_at: createdAtFromNewestRank(22),
    tags: [
      { key: 'carpet', label: 'Carpet' },
      { key: 'dry-care', label: 'Dry care' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: { key: 'carpet-care', label: 'Carpet care' },
      storageGuidance: null,
    },
    image_set_id: 'carpet-refresh-powder',
    slug: 'carpet-refresh-powder',
    packaging: createPackaging('#795b98', '#c8b5d5', 'CR', 'HOU-03', '500g', NOT_FOR_CONSUMPTION),
  },
  {
    id: 23,
    name: 'Window Powder',
    description: 'Dry window-cleaning powder, 350g. Add water; see through your decisions.',
    price_cents: 1195,
    compare_at_price_cents: null,
    category: 'Household',
    stock_count: 39,
    sales_count: 145,
    active: true,
    created_at: createdAtFromNewestRank(23),
    tags: [{ key: 'window-cleaning', label: 'Window cleaning' }],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: { key: 'window-cleaning', label: 'Window cleaning' },
      storageGuidance: null,
    },
    image_set_id: 'window-powder',
    slug: 'window-powder',
    packaging: createPackaging('#4c96b4', '#b6e0ec', 'W', 'HOU-04', '350g', NOT_FOR_CONSUMPTION),
  },
  {
    id: 24,
    name: 'Sock Drawer Powder',
    description: 'Lavender drawer powder, 150g. Socks deserve a formal atmosphere.',
    price_cents: 995,
    compare_at_price_cents: 1295,
    category: 'Household',
    stock_count: 41,
    sales_count: 185,
    active: true,
    created_at: createdAtFromNewestRank(24),
    tags: [
      { key: 'drawer-care', label: 'Drawer care' },
      { key: 'lavender', label: 'Lavender' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: { key: 'drawer-care', label: 'Drawer care' },
      storageGuidance: null,
    },
    image_set_id: 'sock-drawer-powder',
    slug: 'sock-drawer-powder',
    packaging: createPackaging('#7d579a', '#c1a8d1', 'SD', 'HOU-05', '150g', NOT_FOR_CONSUMPTION),
  },
  {
    id: 25,
    name: 'Bookshelf Dusting Powder',
    description: 'Static-lifting dusting powder, 200g. Your unread books will look prepared.',
    price_cents: 1095,
    compare_at_price_cents: null,
    category: 'Household',
    stock_count: 27,
    sales_count: 120,
    active: true,
    created_at: createdAtFromNewestRank(25),
    tags: [{ key: 'dusting', label: 'Dusting' }],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: { key: 'dusting', label: 'Dusting' },
      storageGuidance: null,
    },
    image_set_id: 'bookshelf-dusting-powder',
    slug: 'bookshelf-dusting-powder',
    packaging: createPackaging('#8b7655', '#d2c29f', 'BD', 'HOU-06', '200g', NOT_FOR_CONSUMPTION),
  },
  {
    id: 26,
    name: 'Mop Bucket Powder',
    description: 'Floor-cleaning powder, 750g. A bucket becomes a plan.',
    price_cents: 1495,
    compare_at_price_cents: null,
    category: 'Household',
    stock_count: 36,
    sales_count: 210,
    active: true,
    created_at: createdAtFromNewestRank(26),
    tags: [{ key: 'floor-cleaning', label: 'Floor cleaning' }],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: { key: 'floor-cleaning', label: 'Floor cleaning' },
      storageGuidance: null,
    },
    image_set_id: 'mop-bucket-powder',
    slug: 'mop-bucket-powder',
    packaging: createPackaging('#357f7d', '#acd5ce', 'MB', 'HOU-07', '750g', NOT_FOR_CONSUMPTION),
  },
] as const satisfies readonly CatalogProductDraft[]);
