import { createPackaging, type CatalogProduct, NOT_FOR_CONSUMPTION } from '../model.js';

export const householdProducts = [
  {
    id: 20,
    name: 'Laundry Powder',
    description: 'Cedar laundry powder, 1kg. For clothes that have seen things.',
    price_cents: 1595,
    compare_at_price_cents: null,
    category: 'Household',
    stock_count: 54,
    sales_count: 445,
    newest_rank: 20,
    image_set_id: 'laundry-powder',
    slug: 'laundry-powder',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#2b789d', '#e7eef0', 'LP', 'HOU-01', '1kg'),
  },
  {
    id: 21,
    name: 'Dishwasher Powder',
    description: 'Citrus dishwasher powder, 800g. Plates receive a fresh start.',
    price_cents: 1395,
    compare_at_price_cents: 1695,
    category: 'Household',
    stock_count: 43,
    sales_count: 320,
    newest_rank: 21,
    image_set_id: 'dishwasher-powder',
    slug: 'dishwasher-powder',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#438e89', '#e2eee0', 'DP', 'HOU-02', '800g'),
  },
  {
    id: 22,
    name: 'Carpet Refresh Powder',
    description: 'Dry carpet refresh powder, 500g. Vacuum after the room has reflected.',
    price_cents: 1295,
    compare_at_price_cents: null,
    category: 'Household',
    stock_count: 30,
    sales_count: 160,
    newest_rank: 22,
    image_set_id: 'carpet-refresh-powder',
    slug: 'carpet-refresh-powder',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#795b98', '#c8b5d5', 'CR', 'HOU-03', '500g'),
  },
  {
    id: 23,
    name: 'Window Powder',
    description: 'Dry window-cleaning powder, 350g. Add water; see through your decisions.',
    price_cents: 1195,
    compare_at_price_cents: null,
    category: 'Household',
    stock_count: 39,
    sales_count: 145,
    newest_rank: 23,
    image_set_id: 'window-powder',
    slug: 'window-powder',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#4c96b4', '#b6e0ec', 'W', 'HOU-04', '350g'),
  },
  {
    id: 24,
    name: 'Sock Drawer Powder',
    description: 'Lavender drawer powder, 150g. Socks deserve a formal atmosphere.',
    price_cents: 995,
    compare_at_price_cents: 1295,
    category: 'Household',
    stock_count: 41,
    sales_count: 185,
    newest_rank: 24,
    image_set_id: 'sock-drawer-powder',
    slug: 'sock-drawer-powder',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#7d579a', '#c1a8d1', 'SD', 'HOU-05', '150g'),
  },
  {
    id: 25,
    name: 'Bookshelf Dusting Powder',
    description: 'Static-lifting dusting powder, 200g. Your unread books will look prepared.',
    price_cents: 1095,
    compare_at_price_cents: null,
    category: 'Household',
    stock_count: 27,
    sales_count: 120,
    newest_rank: 25,
    image_set_id: 'bookshelf-dusting-powder',
    slug: 'bookshelf-dusting-powder',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#8b7655', '#d2c29f', 'BD', 'HOU-06', '200g'),
  },
  {
    id: 26,
    name: 'Mop Bucket Powder',
    description: 'Floor-cleaning powder, 750g. A bucket becomes a plan.',
    price_cents: 1495,
    compare_at_price_cents: null,
    category: 'Household',
    stock_count: 36,
    sales_count: 210,
    newest_rank: 26,
    image_set_id: 'mop-bucket-powder',
    slug: 'mop-bucket-powder',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#357f7d', '#acd5ce', 'MB', 'HOU-07', '750g'),
  },

  // Outdoors â€” scenery begins to enter the supply chain.,
] as const satisfies readonly CatalogProduct[];
