import {
  createCatalogProducts,
  createPackaging,
  type CatalogProductDraft,
  NOT_FOR_CONSUMPTION,
} from '../model.js';

export const impossibleProducts = createCatalogProducts([
  {
    id: 39,
    name: 'Powdered Five More Minutes',
    description:
      'Temporal delay powder, conceptual quantity. Use when alarm negotiations continue.',
    price_cents: 2395,
    compare_at_price_cents: null,
    category: 'Impossible',
    stock_count: 16,
    sales_count: 470,
    newest_rank: 39,
    image_set_id: 'powdered-five-more-minutes',
    slug: 'powdered-five-more-minutes',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#62508d', '#b7a2d4', '5M', 'IMP-01', 'conceptual quantity'),
  },
  {
    id: 40,
    name: 'Powdered Gravity',
    description:
      'Portable gravity powder, conceptual quantity. Handle with appropriate downward respect.',
    price_cents: 2995,
    compare_at_price_cents: 3495,
    category: 'Impossible',
    stock_count: 14,
    sales_count: 440,
    newest_rank: 40,
    image_set_id: 'powdered-gravity',
    slug: 'powdered-gravity',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#393e62', '#8288ae', 'G', 'IMP-02', 'conceptual quantity'),
  },
  {
    id: 41,
    name: 'Powdered Silence',
    description:
      'Acoustic silence powder, conceptual quantity. Open away from meaningful conversations.',
    price_cents: 2695,
    compare_at_price_cents: null,
    category: 'Impossible',
    stock_count: 15,
    sales_count: 280,
    newest_rank: 41,
    image_set_id: 'powdered-silence',
    slug: 'powdered-silence',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#55555e', '#d9d8d1', 'S', 'IMP-03', 'conceptual quantity'),
  },
  {
    id: 42,
    name: 'Powdered Moonlight',
    description:
      'Lunar light powder, conceptual quantity. Best stored somewhere without a ceiling.',
    price_cents: 3195,
    compare_at_price_cents: null,
    category: 'Impossible',
    stock_count: 12,
    sales_count: 295,
    newest_rank: 42,
    image_set_id: 'powdered-moonlight',
    slug: 'powdered-moonlight',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#596d9d', '#d8d8e8', 'ML', 'IMP-04', 'conceptual quantity'),
  },
  {
    id: 43,
    name: 'Powdered Weekend',
    description: 'Two-day weekend powder, conceptual quantity. Results vary by calendar.',
    price_cents: 2895,
    compare_at_price_cents: null,
    category: 'Impossible',
    stock_count: 13,
    sales_count: 385,
    newest_rank: 43,
    image_set_id: 'powdered-weekend',
    slug: 'powdered-weekend',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#dd8150', '#edbc75', 'WE', 'IMP-05', 'conceptual quantity'),
  },
  {
    id: 44,
    name: 'Powdered Horizon',
    description:
      'Distant horizon powder, conceptual quantity. Creates perspective without improving forecasts.',
    price_cents: 2795,
    compare_at_price_cents: 3295,
    category: 'Impossible',
    stock_count: 11,
    sales_count: 230,
    newest_rank: 44,
    image_set_id: 'powdered-horizon',
    slug: 'powdered-horizon',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#b46851', '#e4b978', 'HZ', 'IMP-06', 'conceptual quantity'),
  },
  {
    id: 45,
    name: 'Powdered Water',
    description: 'Dehydrated water powder, conceptual quantity. Add water to continue.',
    price_cents: 1995,
    compare_at_price_cents: null,
    category: 'Impossible',
    stock_count: 64,
    sales_count: 1200,
    newest_rank: 45,
    image_set_id: 'powdered-water',
    slug: 'powdered-water',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#287fa6', '#b9e2ee', 'H2O', 'IMP-07', 'conceptual quantity'),
  },
] as const satisfies readonly CatalogProductDraft[]);
