import {
  createCatalogProducts,
  createPackaging,
  type CatalogProductDraft,
  NOT_FOR_CONSUMPTION,
} from '../model.js';

export const impossibleProducts = createCatalogProducts([
  {
    id: 39,
    name: 'Powdered Five More Minutes',
    description:
      'Temporal delay powder, conceptual quantity. Use when alarm negotiations continue.',
    price_cents: 2395,
    compare_at_price_cents: null,
    category: 'Impossible',
    stock_count: 16,
    sales_count: 470,
    active: true,
    created_at: '2025-02-08T00:00:00.000Z',
    tags: [{ key: 'conceptual', label: 'Conceptual' }, { key: 'time', label: 'Time' }],
    specifications: {
      texture: { key: 'powder', label: 'Powder' }, colour: null, source: null,
      intendedUse: null, storageGuidance: null,
    },
    image_set_id: 'powdered-five-more-minutes',
    slug: 'powdered-five-more-minutes',
    packaging: createPackaging('#62508d', '#b7a2d4', '5M', 'IMP-01', 'conceptual quantity', NOT_FOR_CONSUMPTION),
  },
  {
    id: 40,
    name: 'Powdered Gravity',
    description:
      'Portable gravity powder, conceptual quantity. Handle with appropriate downward respect.',
    price_cents: 2995,
    compare_at_price_cents: 3495,
    category: 'Impossible',
    stock_count: 14,
    sales_count: 440,
    active: true,
    created_at: '2025-02-09T00:00:00.000Z',
    tags: [{ key: 'conceptual', label: 'Conceptual' }, { key: 'gravity', label: 'Gravity' }],
    specifications: {
      texture: { key: 'powder', label: 'Powder' }, colour: null, source: null,
      intendedUse: null, storageGuidance: null,
    },
    image_set_id: 'powdered-gravity',
    slug: 'powdered-gravity',
    packaging: createPackaging('#393e62', '#8288ae', 'G', 'IMP-02', 'conceptual quantity', NOT_FOR_CONSUMPTION),
  },
  {
    id: 41,
    name: 'Powdered Silence',
    description:
      'Acoustic silence powder, conceptual quantity. Open away from meaningful conversations.',
    price_cents: 2695,
    compare_at_price_cents: null,
    category: 'Impossible',
    stock_count: 15,
    sales_count: 280,
    active: true,
    created_at: '2025-02-10T00:00:00.000Z',
    tags: [{ key: 'conceptual', label: 'Conceptual' }, { key: 'silence', label: 'Silence' }],
    specifications: {
      texture: { key: 'powder', label: 'Powder' }, colour: null, source: null,
      intendedUse: null, storageGuidance: null,
    },
    image_set_id: 'powdered-silence',
    slug: 'powdered-silence',
    packaging: createPackaging('#55555e', '#d9d8d1', 'S', 'IMP-03', 'conceptual quantity', NOT_FOR_CONSUMPTION),
  },
  {
    id: 42,
    name: 'Powdered Moonlight',
    description:
      'Lunar light powder, conceptual quantity. Best stored somewhere without a ceiling.',
    price_cents: 3195,
    compare_at_price_cents: null,
    category: 'Impossible',
    stock_count: 12,
    sales_count: 295,
    active: true,
    created_at: '2025-02-11T00:00:00.000Z',
    tags: [{ key: 'conceptual', label: 'Conceptual' }, { key: 'moonlight', label: 'Moonlight' }],
    specifications: {
      texture: { key: 'powder', label: 'Powder' }, colour: null, source: null,
      intendedUse: null, storageGuidance: null,
    },
    image_set_id: 'powdered-moonlight',
    slug: 'powdered-moonlight',
    packaging: createPackaging('#596d9d', '#d8d8e8', 'ML', 'IMP-04', 'conceptual quantity', NOT_FOR_CONSUMPTION),
  },
  {
    id: 43,
    name: 'Powdered Weekend',
    description: 'Two-day weekend powder, conceptual quantity. Results vary by calendar.',
    price_cents: 2895,
    compare_at_price_cents: null,
    category: 'Impossible',
    stock_count: 13,
    sales_count: 385,
    active: true,
    created_at: '2025-02-12T00:00:00.000Z',
    tags: [{ key: 'conceptual', label: 'Conceptual' }, { key: 'weekend', label: 'Weekend' }],
    specifications: {
      texture: { key: 'powder', label: 'Powder' }, colour: null, source: null,
      intendedUse: null, storageGuidance: null,
    },
    image_set_id: 'powdered-weekend',
    slug: 'powdered-weekend',
    packaging: createPackaging('#dd8150', '#edbc75', 'WE', 'IMP-05', 'conceptual quantity', NOT_FOR_CONSUMPTION),
  },
  {
    id: 44,
    name: 'Powdered Horizon',
    description:
      'Distant horizon powder, conceptual quantity. Creates perspective without improving forecasts.',
    price_cents: 2795,
    compare_at_price_cents: 3295,
    category: 'Impossible',
    stock_count: 11,
    sales_count: 230,
    active: true,
    created_at: '2025-02-13T00:00:00.000Z',
    tags: [{ key: 'conceptual', label: 'Conceptual' }, { key: 'horizon', label: 'Horizon' }],
    specifications: {
      texture: { key: 'powder', label: 'Powder' }, colour: null, source: null,
      intendedUse: null, storageGuidance: null,
    },
    image_set_id: 'powdered-horizon',
    slug: 'powdered-horizon',
    packaging: createPackaging('#b46851', '#e4b978', 'HZ', 'IMP-06', 'conceptual quantity', NOT_FOR_CONSUMPTION),
  },
  {
    id: 45,
    name: 'Powdered Water',
    description: 'Dehydrated water powder, conceptual quantity. Add water to continue.',
    price_cents: 1995,
    compare_at_price_cents: null,
    category: 'Impossible',
    stock_count: 64,
    sales_count: 1200,
    active: true,
    created_at: '2025-02-14T00:00:00.000Z',
    tags: [{ key: 'conceptual', label: 'Conceptual' }, { key: 'water', label: 'Water' }],
    specifications: {
      texture: { key: 'powder', label: 'Powder' }, colour: null, source: null,
      intendedUse: null, storageGuidance: null,
    },
    image_set_id: 'powdered-water',
    slug: 'powdered-water',
    packaging: createPackaging('#287fa6', '#b9e2ee', 'H2O', 'IMP-07', 'conceptual quantity', NOT_FOR_CONSUMPTION),
  },
  {
    id: 49,
    name: 'Moon Rock',
    description: 'Certified lunar rock powder. Gravity becomes a suggestion after opening.',
    price_cents: 2500000,
    compare_at_price_cents: null,
    category: 'Impossible',
    stock_count: 1,
    sales_count: 49,
    active: true,
    created_at: '2025-02-18T00:00:00.000Z',
    tags: [{ key: 'conceptual', label: 'Conceptual' }, { key: 'lunar', label: 'Lunar' }],
    specifications: {
      texture: { key: 'powder', label: 'Powder' }, colour: null, source: null,
      intendedUse: null, storageGuidance: null,
    },
    image_set_id: 'moon-rock',
    slug: 'moon-rock',
    packaging: createPackaging('#5e6380', '#d4d4df', 'MR', 'IMP-08', 'conceptual quantity', NOT_FOR_CONSUMPTION),
  },
] as const satisfies readonly CatalogProductDraft[]);
