import { createPackaging, type CatalogProduct, NOT_FOR_CONSUMPTION } from '../model.js';

export const outdoorsProducts = [
  {
    id: 27,
    name: 'Powdered Campfire',
    description: 'Smoky campfire-scented powder, 200g. Sprinkle nowhere near an actual flame.',
    price_cents: 1695,
    compare_at_price_cents: null,
    category: 'Outdoors',
    stock_count: 24,
    sales_count: 390,
    newest_rank: 27,
    image_set_id: 'powdered-campfire',
    slug: 'powdered-campfire',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#b6452d', '#715044', 'CF', 'OUT-01', '200g'),
  },
  {
    id: 28,
    name: 'Powdered Beach',
    description: 'Sea-air beach ambience powder, 250g. Sand-free by administrative decree.',
    price_cents: 1795,
    compare_at_price_cents: 2195,
    category: 'Outdoors',
    stock_count: 25,
    sales_count: 340,
    newest_rank: 28,
    image_set_id: 'powdered-beach',
    slug: 'powdered-beach',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#2f97a9', '#e3cb8c', 'B', 'OUT-02', '250g'),
  },
  {
    id: 29,
    name: 'Trail Dust Powder',
    description: 'Pine trail ambience powder, 180g. For indoor routes with no map.',
    price_cents: 1395,
    compare_at_price_cents: null,
    category: 'Outdoors',
    stock_count: 28,
    sales_count: 190,
    newest_rank: 29,
    image_set_id: 'trail-dust-powder',
    slug: 'trail-dust-powder',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#557447', '#9a8261', 'TD', 'OUT-03', '180g'),
  },
  {
    id: 30,
    name: 'Morning Fog Powder',
    description: 'Atmospheric fog-effect powder, 120g. Visibility sold in a separate bag.',
    price_cents: 1595,
    compare_at_price_cents: null,
    category: 'Outdoors',
    stock_count: 22,
    sales_count: 175,
    newest_rank: 30,
    image_set_id: 'morning-fog-powder',
    slug: 'morning-fog-powder',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#69879b', '#d3dfe3', 'MF', 'OUT-04', '120g'),
  },
  {
    id: 31,
    name: 'Pine Needle Powder',
    description: 'Forest-floor scent powder, 150g. Hike adjacent, without boots.',
    price_cents: 1295,
    compare_at_price_cents: 1495,
    category: 'Outdoors',
    stock_count: 34,
    sales_count: 205,
    newest_rank: 31,
    image_set_id: 'pine-needle-powder',
    slug: 'pine-needle-powder',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#38634d', '#7b9b69', 'PN', 'OUT-05', '150g'),
  },
  {
    id: 32,
    name: 'Summit Air Powder',
    description: 'Crisp alpine ambience powder, 100g. Open only at ground level.',
    price_cents: 1895,
    compare_at_price_cents: null,
    category: 'Outdoors',
    stock_count: 19,
    sales_count: 135,
    newest_rank: 32,
    image_set_id: 'summit-air-powder',
    slug: 'summit-air-powder',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#557da8', '#d4e3ed', 'SA', 'OUT-06', '100g'),
  },

  // Questionable â€” domestic concepts receive powders.,
] as const satisfies readonly CatalogProduct[];
