import {
  createCatalogProducts,
  createPackaging,
  createdAtFromNewestRank,
  type CatalogProductDraft,
  NOT_FOR_CONSUMPTION,
} from '../model.js';

export const outdoorsProducts = createCatalogProducts([
  {
    id: 27,
    name: 'Campfire',
    description: 'Smoky campfire-scented powder, 200g. Sprinkle nowhere near an actual flame.',
    price_cents: 1695,
    compare_at_price_cents: null,
    category: 'Outdoors',
    stock_count: 24,
    sales_count: 390,
    active: true,
    created_at: createdAtFromNewestRank(27),
    tags: [
      { key: 'outdoor', label: 'Outdoor' },
      { key: 'campfire', label: 'Campfire' },
      { key: 'smoky', label: 'Smoky' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: { key: 'ambience', label: 'Ambience' },
      storageGuidance: null,
    },
    image_set_id: 'powdered-campfire',
    slug: 'powdered-campfire',
    packaging: createPackaging('#b6452d', '#715044', 'CF', 'OUT-01', '200g', NOT_FOR_CONSUMPTION),
  },
  {
    id: 28,
    name: 'Powdered Beach',
    description: 'Sea-air beach ambience powder, 250g. Sand-free by administrative decree.',
    price_cents: 1795,
    compare_at_price_cents: 2195,
    category: 'Outdoors',
    stock_count: 25,
    sales_count: 340,
    active: true,
    created_at: createdAtFromNewestRank(28),
    tags: [
      { key: 'outdoor', label: 'Outdoor' },
      { key: 'beach', label: 'Beach' },
      { key: 'sea-air', label: 'Sea air' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: { key: 'ambience', label: 'Ambience' },
      storageGuidance: null,
    },
    image_set_id: 'powdered-beach',
    slug: 'powdered-beach',
    packaging: createPackaging('#2f97a9', '#e3cb8c', 'B', 'OUT-02', '250g', NOT_FOR_CONSUMPTION),
  },
  {
    id: 29,
    name: 'Trail Dust Powder',
    description: 'Pine trail ambience powder, 180g. For indoor routes with no map.',
    price_cents: 1395,
    compare_at_price_cents: null,
    category: 'Outdoors',
    stock_count: 28,
    sales_count: 190,
    active: true,
    created_at: createdAtFromNewestRank(29),
    tags: [
      { key: 'outdoor', label: 'Outdoor' },
      { key: 'trail', label: 'Trail' },
      { key: 'pine', label: 'Pine' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: { key: 'ambience', label: 'Ambience' },
      storageGuidance: null,
    },
    image_set_id: 'trail-dust-powder',
    slug: 'trail-dust-powder',
    packaging: createPackaging('#557447', '#9a8261', 'TD', 'OUT-03', '180g', NOT_FOR_CONSUMPTION),
  },
  {
    id: 30,
    name: 'Morning Fog Powder',
    description: 'Atmospheric fog-effect powder, 120g. Visibility sold in a separate bag.',
    price_cents: 1595,
    compare_at_price_cents: null,
    category: 'Outdoors',
    stock_count: 22,
    sales_count: 175,
    active: true,
    created_at: createdAtFromNewestRank(30),
    tags: [
      { key: 'outdoor', label: 'Outdoor' },
      { key: 'fog', label: 'Fog' },
      { key: 'atmospheric', label: 'Atmospheric' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: { key: 'atmospheric-effect', label: 'Atmospheric effect' },
      storageGuidance: null,
    },
    image_set_id: 'morning-fog-powder',
    slug: 'morning-fog-powder',
    packaging: createPackaging('#69879b', '#d3dfe3', 'MF', 'OUT-04', '120g', NOT_FOR_CONSUMPTION),
  },
  {
    id: 31,
    name: 'Pine Needle Powder',
    description: 'Forest-floor scent powder, 150g. Hike adjacent, without boots.',
    price_cents: 1295,
    compare_at_price_cents: 1495,
    category: 'Outdoors',
    stock_count: 34,
    sales_count: 205,
    active: true,
    created_at: createdAtFromNewestRank(31),
    tags: [
      { key: 'outdoor', label: 'Outdoor' },
      { key: 'pine', label: 'Pine' },
      { key: 'forest-floor', label: 'Forest floor' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: { key: 'ambience', label: 'Ambience' },
      storageGuidance: null,
    },
    image_set_id: 'pine-needle-powder',
    slug: 'pine-needle-powder',
    packaging: createPackaging('#38634d', '#7b9b69', 'PN', 'OUT-05', '150g', NOT_FOR_CONSUMPTION),
  },
  {
    id: 32,
    name: 'Summit Air Powder',
    description: 'Crisp alpine ambience powder, 100g. Open only at ground level.',
    price_cents: 1895,
    compare_at_price_cents: null,
    category: 'Outdoors',
    stock_count: 19,
    sales_count: 135,
    active: true,
    created_at: createdAtFromNewestRank(32),
    tags: [
      { key: 'outdoor', label: 'Outdoor' },
      { key: 'summit', label: 'Summit' },
      { key: 'alpine', label: 'Alpine' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: { key: 'ambience', label: 'Ambience' },
      storageGuidance: null,
    },
    image_set_id: 'summit-air-powder',
    slug: 'summit-air-powder',
    packaging: createPackaging('#557da8', '#d4e3ed', 'SA', 'OUT-06', '100g', NOT_FOR_CONSUMPTION),
  },

  // Questionable â€” domestic concepts receive powders.,
] as const satisfies readonly CatalogProductDraft[]);
