import { createCatalogProducts, createPackaging, type CatalogProductDraft } from '../model.js';

export const pantryProducts = createCatalogProducts([
  {
    id: 1,
    name: 'Protein Powder',
    description:
      'Vanilla whey protein powder, 900g. For shakes, oats, and taking breakfast unusually seriously.',
    price_cents: 3295,
    compare_at_price_cents: null,
    category: 'Pantry Staples',
    stock_count: 42,
    sales_count: 680,
    active: true,
    created_at: '2025-01-01T00:00:00.000Z',
    tags: [
      { key: 'protein', label: 'Protein' },
      { key: 'vanilla', label: 'Vanilla' },
      { key: 'whey', label: 'Whey' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: { key: 'whey', label: 'Whey' },
      intendedUse: { key: 'shakes', label: 'Shakes' },
      storageGuidance: null,
    },
    image_set_id: 'protein-powder',
    slug: 'protein-powder',
    packaging: createPackaging('#d9583b', '#f4dfb5', 'P', 'PAN-01', '900g'),
  },
  {
    id: 2,
    name: 'Powdered Oats',
    description: 'Stone-ground oat flour, 750g. Porridge plans with less chewing.',
    price_cents: 1195,
    compare_at_price_cents: null,
    category: 'Pantry Staples',
    stock_count: 56,
    sales_count: 410,
    active: true,
    created_at: '2025-01-02T00:00:00.000Z',
    tags: [
      { key: 'oat', label: 'Oat' },
      { key: 'flour', label: 'Flour' },
      { key: 'stone-ground', label: 'Stone-ground' },
    ],
    specifications: {
      texture: { key: 'flour', label: 'Flour' },
      colour: null,
      source: { key: 'oat', label: 'Oat' },
      intendedUse: { key: 'porridge', label: 'Porridge' },
      storageGuidance: null,
    },
    image_set_id: 'powdered-oats',
    slug: 'powdered-oats',
    packaging: createPackaging('#d5a12d', '#dac18b', 'O', 'PAN-02', '750g'),
  },
  {
    id: 3,
    name: 'Cocoa Powder',
    description: 'Deep cocoa powder, 250g. Brownies, hot drinks, and controlled drama.',
    price_cents: 895,
    compare_at_price_cents: 1095,
    category: 'Pantry Staples',
    stock_count: 38,
    sales_count: 495,
    active: true,
    created_at: '2025-01-03T00:00:00.000Z',
    tags: [{ key: 'cocoa', label: 'Cocoa' }],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: { key: 'cocoa', label: 'Cocoa' },
      intendedUse: { key: 'baking', label: 'Baking' },
      storageGuidance: null,
    },
    image_set_id: 'cocoa-powder',
    slug: 'cocoa-powder',
    packaging: createPackaging('#71412c', '#6a3828', 'C', 'PAN-03', '250g'),
  },
  {
    id: 4,
    name: 'Powdered Peanut Butter',
    description:
      'Defatted peanut butter powder, 180g. Stir into sauces or rebuild a sandwich internally.',
    price_cents: 1095,
    compare_at_price_cents: null,
    category: 'Pantry Staples',
    stock_count: 44,
    sales_count: 360,
    active: true,
    created_at: '2025-01-04T00:00:00.000Z',
    tags: [
      { key: 'peanut', label: 'Peanut' },
      { key: 'peanut-butter', label: 'Peanut butter' },
      { key: 'defatted', label: 'Defatted' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: { key: 'peanut', label: 'Peanut' },
      intendedUse: { key: 'sauces', label: 'Sauces' },
      storageGuidance: null,
    },
    image_set_id: 'powdered-peanut-butter',
    slug: 'powdered-peanut-butter',
    packaging: createPackaging('#d68132', '#d5ad68', 'PB', 'PAN-04', '180g'),
  },
  {
    id: 5,
    name: 'Tomato Powder',
    description: 'Concentrated tomato powder, 200g. Soup, sauces, and emergency redness.',
    price_cents: 795,
    compare_at_price_cents: null,
    category: 'Pantry Staples',
    stock_count: 47,
    sales_count: 290,
    active: true,
    created_at: '2025-01-05T00:00:00.000Z',
    tags: [{ key: 'tomato', label: 'Tomato' }],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: { key: 'tomato', label: 'Tomato' },
      intendedUse: { key: 'soups-and-sauces', label: 'Soups and sauces' },
      storageGuidance: null,
    },
    image_set_id: 'tomato-powder',
    slug: 'tomato-powder',
    packaging: createPackaging('#c9483d', '#d85643', 'T', 'PAN-05', '200g'),
  },
  {
    id: 6,
    name: 'Mushroom Powder',
    description: 'Dried porcini powder, 100g. Savoury depth without visible mushrooms.',
    price_cents: 1295,
    compare_at_price_cents: 1495,
    category: 'Pantry Staples',
    stock_count: 31,
    sales_count: 275,
    active: true,
    created_at: '2025-01-06T00:00:00.000Z',
    tags: [
      { key: 'mushroom', label: 'Mushroom' },
      { key: 'porcini', label: 'Porcini' },
      { key: 'dried', label: 'Dried' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: { key: 'porcini', label: 'Porcini' },
      intendedUse: null,
      storageGuidance: null,
    },
    image_set_id: 'mushroom-powder',
    slug: 'mushroom-powder',
    packaging: createPackaging('#8a6847', '#9a7e57', 'M', 'PAN-06', '100g'),
  },
  {
    id: 7,
    name: 'Roasted Garlic Powder',
    description: 'Slow-roasted garlic powder, 120g. Dinner gets its paperwork done.',
    price_cents: 695,
    compare_at_price_cents: null,
    category: 'Pantry Staples',
    stock_count: 63,
    sales_count: 390,
    active: true,
    created_at: '2025-01-07T00:00:00.000Z',
    tags: [
      { key: 'garlic', label: 'Garlic' },
      { key: 'roasted', label: 'Roasted' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: { key: 'garlic', label: 'Garlic' },
      intendedUse: null,
      storageGuidance: null,
    },
    image_set_id: 'roasted-garlic-powder',
    slug: 'roasted-garlic-powder',
    packaging: createPackaging('#b67e2c', '#d8bf85', 'G', 'PAN-07', '120g'),
  },

  // Performance â€” still recognisable, increasingly committed.,
] as const satisfies readonly CatalogProductDraft[]);
