import { createPackaging, type CatalogProduct } from '../model.js';

export const pantryProducts = [
  {
    id: 1,
    name: 'Protein Powder',
    description:
      'Vanilla whey protein powder, 900g. For shakes, oats, and taking breakfast unusually seriously.',
    price_cents: 3295,
    compare_at_price_cents: null,
    category: 'Pantry Staples',
    stock_count: 42,
    sales_count: 680,
    newest_rank: 1,
    image_set_id: 'protein-powder',
    slug: 'protein-powder',
    consumption_warning: null,
    packaging: createPackaging('#d9583b', '#f4dfb5', 'P', 'PAN-01', '900g'),
  },
  {
    id: 2,
    name: 'Powdered Oats',
    description: 'Stone-ground oat flour, 750g. Porridge plans with less chewing.',
    price_cents: 1195,
    compare_at_price_cents: null,
    category: 'Pantry Staples',
    stock_count: 56,
    sales_count: 410,
    newest_rank: 2,
    image_set_id: 'powdered-oats',
    slug: 'powdered-oats',
    consumption_warning: null,
    packaging: createPackaging('#d5a12d', '#dac18b', 'O', 'PAN-02', '750g'),
  },
  {
    id: 3,
    name: 'Cocoa Powder',
    description: 'Deep cocoa powder, 250g. Brownies, hot drinks, and controlled drama.',
    price_cents: 895,
    compare_at_price_cents: 1095,
    category: 'Pantry Staples',
    stock_count: 38,
    sales_count: 495,
    newest_rank: 3,
    image_set_id: 'cocoa-powder',
    slug: 'cocoa-powder',
    consumption_warning: null,
    packaging: createPackaging('#71412c', '#6a3828', 'C', 'PAN-03', '250g'),
  },
  {
    id: 4,
    name: 'Powdered Peanut Butter',
    description:
      'Defatted peanut butter powder, 180g. Stir into sauces or rebuild a sandwich internally.',
    price_cents: 1095,
    compare_at_price_cents: null,
    category: 'Pantry Staples',
    stock_count: 44,
    sales_count: 360,
    newest_rank: 4,
    image_set_id: 'powdered-peanut-butter',
    slug: 'powdered-peanut-butter',
    consumption_warning: null,
    packaging: createPackaging('#d68132', '#d5ad68', 'PB', 'PAN-04', '180g'),
  },
  {
    id: 5,
    name: 'Tomato Powder',
    description: 'Concentrated tomato powder, 200g. Soup, sauces, and emergency redness.',
    price_cents: 795,
    compare_at_price_cents: null,
    category: 'Pantry Staples',
    stock_count: 47,
    sales_count: 290,
    newest_rank: 5,
    image_set_id: 'tomato-powder',
    slug: 'tomato-powder',
    consumption_warning: null,
    packaging: createPackaging('#c9483d', '#d85643', 'T', 'PAN-05', '200g'),
  },
  {
    id: 6,
    name: 'Mushroom Powder',
    description: 'Dried porcini powder, 100g. Savoury depth without visible mushrooms.',
    price_cents: 1295,
    compare_at_price_cents: 1495,
    category: 'Pantry Staples',
    stock_count: 31,
    sales_count: 275,
    newest_rank: 6,
    image_set_id: 'mushroom-powder',
    slug: 'mushroom-powder',
    consumption_warning: null,
    packaging: createPackaging('#8a6847', '#9a7e57', 'M', 'PAN-06', '100g'),
  },
  {
    id: 7,
    name: 'Roasted Garlic Powder',
    description: 'Slow-roasted garlic powder, 120g. Dinner gets its paperwork done.',
    price_cents: 695,
    compare_at_price_cents: null,
    category: 'Pantry Staples',
    stock_count: 63,
    sales_count: 390,
    newest_rank: 7,
    image_set_id: 'roasted-garlic-powder',
    slug: 'roasted-garlic-powder',
    consumption_warning: null,
    packaging: createPackaging('#b67e2c', '#d8bf85', 'G', 'PAN-07', '120g'),
  },

  // Performance â€” still recognisable, increasingly committed.,
] as const satisfies readonly CatalogProduct[];
