import { createPackaging, type CatalogProduct } from '../model.js';

export const performanceProducts = [
  {
    id: 8,
    name: 'Electrolyte Powder',
    description: 'Citrus electrolyte mix, 300g. Add to water after ordinary exertion.',
    price_cents: 1495,
    compare_at_price_cents: null,
    category: 'Performance',
    stock_count: 50,
    sales_count: 540,
    newest_rank: 8,
    image_set_id: 'electrolyte-powder',
    slug: 'electrolyte-powder',
    consumption_warning: null,
    packaging: createPackaging('#2476a8', '#b8dc48', 'E', 'PER-01', '300g'),
  },
  {
    id: 9,
    name: 'Recovery Cocoa',
    description:
      'Cocoa recovery drink mix, 500g. Chocolate-flavoured post-exercise administration.',
    price_cents: 2395,
    compare_at_price_cents: 2795,
    category: 'Performance',
    stock_count: 29,
    sales_count: 340,
    newest_rank: 9,
    image_set_id: 'recovery-cocoa',
    slug: 'recovery-cocoa',
    consumption_warning: null,
    packaging: createPackaging('#51362f', '#8b583e', 'RC', 'PER-02', '500g'),
  },
  {
    id: 10,
    name: 'Beetroot Powder',
    description: 'Beetroot powder, 250g. Bright colour for drinks with personal objectives.',
    price_cents: 1395,
    compare_at_price_cents: null,
    category: 'Performance',
    stock_count: 35,
    sales_count: 215,
    newest_rank: 10,
    image_set_id: 'beetroot-powder',
    slug: 'beetroot-powder',
    consumption_warning: null,
    packaging: createPackaging('#a82d4b', '#bd3555', 'B', 'PER-03', '250g'),
  },
  {
    id: 11,
    name: 'Pea Protein Powder',
    description: 'Unflavoured pea protein powder, 750g. A quiet, practical scoop.',
    price_cents: 2695,
    compare_at_price_cents: null,
    category: 'Performance',
    stock_count: 34,
    sales_count: 305,
    newest_rank: 11,
    image_set_id: 'pea-protein-powder',
    slug: 'pea-protein-powder',
    consumption_warning: null,
    packaging: createPackaging('#658a47', '#c5d69c', 'PP', 'PER-04', '750g'),
  },
  {
    id: 12,
    name: 'Banana Powder',
    description: 'Freeze-dried banana powder, 200g. Smoothies without banana logistics.',
    price_cents: 1295,
    compare_at_price_cents: 1595,
    category: 'Performance',
    stock_count: 40,
    sales_count: 330,
    newest_rank: 12,
    image_set_id: 'banana-powder',
    slug: 'banana-powder',
    consumption_warning: null,
    packaging: createPackaging('#e0b82f', '#e5ce65', 'B', 'PER-05', '200g'),
  },
  {
    id: 13,
    name: 'Oat Milk Powder',
    description: 'Barista oat milk powder, 400g. Foam arrives after a measured delay.',
    price_cents: 1795,
    compare_at_price_cents: null,
    category: 'Performance',
    stock_count: 45,
    sales_count: 365,
    newest_rank: 13,
    image_set_id: 'oat-milk-powder',
    slug: 'oat-milk-powder',
    consumption_warning: null,
    packaging: createPackaging('#b8894b', '#e3d2b0', 'OM', 'PER-06', '400g'),
  },

  // Drinks â€” normal objects, granulated.,
] as const satisfies readonly CatalogProduct[];
