import {
  createCatalogProducts,
  createPackaging,
  type CatalogProductDraft,
  NOT_FOR_CONSUMPTION,
} from '../model.js';

export const questionableProducts = createCatalogProducts([
  {
    id: 33,
    name: 'House',
    description:
      'Architectural house powder, conceptual quantity. Add nothing; it is already a house.',
    price_cents: 2495,
    compare_at_price_cents: null,
    category: 'Questionable',
    stock_count: 17,
    sales_count: 260,
    active: true,
    created_at: '2025-02-02T00:00:00.000Z',
    tags: [
      { key: 'conceptual', label: 'Conceptual' },
      { key: 'house', label: 'House' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: null,
      storageGuidance: null,
    },
    image_set_id: 'powdered-house',
    slug: 'powdered-house',
    packaging: createPackaging(
      '#a96d46',
      '#d6c1a8',
      'H',
      'QUE-01',
      'conceptual quantity',
      NOT_FOR_CONSUMPTION,
    ),
  },
  {
    id: 34,
    name: 'Internet',
    description: 'Wireless-network powder, conceptual quantity. For rooms requesting more bars.',
    price_cents: 2295,
    compare_at_price_cents: 2795,
    category: 'Questionable',
    stock_count: 21,
    sales_count: 330,
    active: true,
    created_at: '2025-02-03T00:00:00.000Z',
    tags: [
      { key: 'conceptual', label: 'Conceptual' },
      { key: 'internet', label: 'Internet' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: null,
      storageGuidance: null,
    },
    image_set_id: 'powdered-wifi',
    slug: 'powdered-wifi',
    packaging: createPackaging(
      '#3e75ad',
      '#a4c8e4',
      'WF',
      'QUE-02',
      'conceptual quantity',
      NOT_FOR_CONSUMPTION,
    ),
  },
  {
    id: 35,
    name: 'Powdered Tuesday',
    description: 'Weekday powder, conceptual quantity. Apply only when Monday has concluded.',
    price_cents: 1995,
    compare_at_price_cents: null,
    category: 'Questionable',
    stock_count: 26,
    sales_count: 245,
    active: true,
    created_at: '2025-02-04T00:00:00.000Z',
    tags: [
      { key: 'conceptual', label: 'Conceptual' },
      { key: 'tuesday', label: 'Tuesday' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: null,
      storageGuidance: null,
    },
    image_set_id: 'powdered-tuesday',
    slug: 'powdered-tuesday',
    packaging: createPackaging(
      '#4e77a7',
      '#bbc9da',
      'TU',
      'QUE-03',
      'conceptual quantity',
      NOT_FOR_CONSUMPTION,
    ),
  },
  {
    id: 36,
    name: 'Powdered Meeting',
    description: 'Corporate meeting powder, conceptual quantity. Contains no actionable minutes.',
    price_cents: 2195,
    compare_at_price_cents: null,
    category: 'Questionable',
    stock_count: 18,
    sales_count: 155,
    active: true,
    created_at: '2025-02-05T00:00:00.000Z',
    tags: [
      { key: 'conceptual', label: 'Conceptual' },
      { key: 'meeting', label: 'Meeting' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: null,
      storageGuidance: null,
    },
    image_set_id: 'powdered-meeting',
    slug: 'powdered-meeting',
    packaging: createPackaging(
      '#5e6472',
      '#b7bac1',
      'MT',
      'QUE-04',
      'conceptual quantity',
      NOT_FOR_CONSUMPTION,
    ),
  },
  {
    id: 37,
    name: 'Powdered Spare Key',
    description: 'Emergency key powder, conceptual quantity. Keep somewhere extremely memorable.',
    price_cents: 1695,
    compare_at_price_cents: 1995,
    category: 'Questionable',
    stock_count: 23,
    sales_count: 180,
    active: true,
    created_at: '2025-02-06T00:00:00.000Z',
    tags: [
      { key: 'conceptual', label: 'Conceptual' },
      { key: 'spare-key', label: 'Spare key' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: null,
      storageGuidance: null,
    },
    image_set_id: 'powdered-spare-key',
    slug: 'powdered-spare-key',
    packaging: createPackaging(
      '#9a7727',
      '#d3b969',
      'SK',
      'QUE-05',
      'conceptual quantity',
      NOT_FOR_CONSUMPTION,
    ),
  },
  {
    id: 38,
    name: 'Powdered Queue',
    description: 'British queue powder, conceptual quantity. First come, first finely considered.',
    price_cents: 2095,
    compare_at_price_cents: null,
    category: 'Questionable',
    stock_count: 20,
    sales_count: 140,
    active: true,
    created_at: '2025-02-07T00:00:00.000Z',
    tags: [
      { key: 'conceptual', label: 'Conceptual' },
      { key: 'queue', label: 'Queue' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: null,
      storageGuidance: null,
    },
    image_set_id: 'powdered-queue',
    slug: 'powdered-queue',
    packaging: createPackaging(
      '#7a5e8f',
      '#c7b4d4',
      'Q',
      'QUE-06',
      'conceptual quantity',
      NOT_FOR_CONSUMPTION,
    ),
  },
  {
    id: 46,
    name: 'Boat',
    description:
      'A whole boat, reduced to powder. Life jacket remains an unsolved logistics problem.',
    price_cents: 89995,
    compare_at_price_cents: null,
    category: 'Questionable',
    stock_count: 8,
    sales_count: 46,
    active: true,
    created_at: '2025-02-15T00:00:00.000Z',
    tags: [
      { key: 'conceptual', label: 'Conceptual' },
      { key: 'boat', label: 'Boat' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: null,
      storageGuidance: null,
    },
    image_set_id: 'boat',
    slug: 'boat',
    packaging: createPackaging(
      '#176b93',
      '#74b7cf',
      'BT',
      'QUE-07',
      'conceptual quantity',
      NOT_FOR_CONSUMPTION,
    ),
  },
  {
    id: 47,
    name: 'Plane',
    description:
      'Commercial aircraft powder, conceptual quantity. Boarding begins after reconstitution.',
    price_cents: 249995,
    compare_at_price_cents: null,
    category: 'Questionable',
    stock_count: 4,
    sales_count: 47,
    active: true,
    created_at: '2025-02-16T00:00:00.000Z',
    tags: [
      { key: 'conceptual', label: 'Conceptual' },
      { key: 'plane', label: 'Plane' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: null,
      storageGuidance: null,
    },
    image_set_id: 'plane',
    slug: 'plane',
    packaging: createPackaging(
      '#4c7594',
      '#cad7e3',
      'PL',
      'QUE-08',
      'conceptual quantity',
      NOT_FOR_CONSUMPTION,
    ),
  },
  {
    id: 48,
    name: 'MacBook Pro',
    description:
      'Professional laptop powder, conceptual quantity. Ports sold as an emotional concept.',
    price_cents: 199999,
    compare_at_price_cents: null,
    category: 'Questionable',
    stock_count: 6,
    sales_count: 48,
    active: true,
    created_at: '2025-02-17T00:00:00.000Z',
    tags: [
      { key: 'conceptual', label: 'Conceptual' },
      { key: 'laptop', label: 'Laptop' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: null,
      storageGuidance: null,
    },
    image_set_id: 'macbook-pro',
    slug: 'macbook-pro',
    packaging: createPackaging(
      '#3e4148',
      '#a8adb5',
      'MBP',
      'QUE-09',
      'conceptual quantity',
      NOT_FOR_CONSUMPTION,
    ),
  },
  {
    id: 50,
    name: 'Diamond',
    description: 'A diamond in powder form. Permanence, now with a scoop.',
    price_cents: 499999,
    compare_at_price_cents: null,
    category: 'Questionable',
    stock_count: 3,
    sales_count: 50,
    active: true,
    created_at: '2025-02-19T00:00:00.000Z',
    tags: [
      { key: 'conceptual', label: 'Conceptual' },
      { key: 'diamond', label: 'Diamond' },
    ],
    specifications: {
      texture: { key: 'powder', label: 'Powder' },
      colour: null,
      source: null,
      intendedUse: null,
      storageGuidance: null,
    },
    image_set_id: 'diamond',
    slug: 'diamond',
    packaging: createPackaging(
      '#75d7d5',
      '#e4ffff',
      'D',
      'QUE-10',
      'conceptual quantity',
      NOT_FOR_CONSUMPTION,
    ),
  },

  // Impossible â€” hero product is intentionally the bestseller.,
] as const satisfies readonly CatalogProductDraft[]);
