import {
  createCatalogProducts,
  createPackaging,
  type CatalogProductDraft,
  NOT_FOR_CONSUMPTION,
} from '../model.js';

export const questionableProducts = createCatalogProducts([
  {
    id: 33,
    name: 'Powdered House',
    description:
      'Architectural house powder, conceptual quantity. Add nothing; it is already a house.',
    price_cents: 2495,
    compare_at_price_cents: null,
    category: 'Questionable',
    stock_count: 17,
    sales_count: 260,
    newest_rank: 33,
    image_set_id: 'powdered-house',
    slug: 'powdered-house',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#a96d46', '#d6c1a8', 'H', 'QUE-01', 'conceptual quantity'),
  },
  {
    id: 34,
    name: 'Powdered Wi-Fi',
    description: 'Wireless-network powder, conceptual quantity. For rooms requesting more bars.',
    price_cents: 2295,
    compare_at_price_cents: 2795,
    category: 'Questionable',
    stock_count: 21,
    sales_count: 330,
    newest_rank: 34,
    image_set_id: 'powdered-wifi',
    slug: 'powdered-wifi',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#3e75ad', '#a4c8e4', 'WF', 'QUE-02', 'conceptual quantity'),
  },
  {
    id: 35,
    name: 'Powdered Tuesday',
    description: 'Weekday powder, conceptual quantity. Apply only when Monday has concluded.',
    price_cents: 1995,
    compare_at_price_cents: null,
    category: 'Questionable',
    stock_count: 26,
    sales_count: 245,
    newest_rank: 35,
    image_set_id: 'powdered-tuesday',
    slug: 'powdered-tuesday',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#4e77a7', '#bbc9da', 'TU', 'QUE-03', 'conceptual quantity'),
  },
  {
    id: 36,
    name: 'Powdered Meeting',
    description: 'Corporate meeting powder, conceptual quantity. Contains no actionable minutes.',
    price_cents: 2195,
    compare_at_price_cents: null,
    category: 'Questionable',
    stock_count: 18,
    sales_count: 155,
    newest_rank: 36,
    image_set_id: 'powdered-meeting',
    slug: 'powdered-meeting',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#5e6472', '#b7bac1', 'MT', 'QUE-04', 'conceptual quantity'),
  },
  {
    id: 37,
    name: 'Powdered Spare Key',
    description: 'Emergency key powder, conceptual quantity. Keep somewhere extremely memorable.',
    price_cents: 1695,
    compare_at_price_cents: 1995,
    category: 'Questionable',
    stock_count: 23,
    sales_count: 180,
    newest_rank: 37,
    image_set_id: 'powdered-spare-key',
    slug: 'powdered-spare-key',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#9a7727', '#d3b969', 'SK', 'QUE-05', 'conceptual quantity'),
  },
  {
    id: 38,
    name: 'Powdered Queue',
    description: 'British queue powder, conceptual quantity. First come, first finely considered.',
    price_cents: 2095,
    compare_at_price_cents: null,
    category: 'Questionable',
    stock_count: 20,
    sales_count: 140,
    newest_rank: 38,
    image_set_id: 'powdered-queue',
    slug: 'powdered-queue',
    consumption_warning: NOT_FOR_CONSUMPTION,
    packaging: createPackaging('#7a5e8f', '#c7b4d4', 'Q', 'QUE-06', 'conceptual quantity'),
  },

  // Impossible â€” hero product is intentionally the bestseller.,
] as const satisfies readonly CatalogProductDraft[]);
